import asyncio
import os
import aiohttp

titre = "Subdirectory Scanner"
os.system(f"title {titre}")

def init_js_file():
    with open('Scanner_VDP.js', 'w') as js_file:
        js_file.write('// JavaScript file generated by Python script\n')
        js_file.write('console.log("Scanner_VDP.js generated!");\n\n')

def write_to_js_file(url):
    with open('Scanner_VDP.js', 'a') as js_file:
        js_file.write(f'// Found: {url}\n')

async def scan_directory(session, base_url, directory):
    url = f"{base_url}/{directory}"
    print(f'[+] Testing: {url}')
    try:
        async with session.get(url, timeout=5) as response:
            if response.status != 404:
                print(f'[✓] Found: {url} (Status: {response.status})')
                write_to_js_file(url)
            else:
                print(f'[-] Not found: {url} (Status: {response.status})')
    except Exception as e:
        print(f'[!] Error scanning {url}: {e}')

async def domain_scanner(base_url, directories):
    print(f'Starting scan for {base_url}...\n')
    init_js_file()

    async with aiohttp.ClientSession() as session:
        tasks = [scan_directory(session, base_url, directory) for directory in directories]
        await asyncio.gather(*tasks)

    print(f'\nScan finished for {base_url}. Scanner_VDP.js generated.')

def main():
    print("Created by X-VDP-X\n")
    domain = input("Enter the domain name (ex: google.com): ").strip().strip('/')

    if not domain:
        print("Domaine vide, sortie.")
        return

    # Construire base_url avec https://
    base_url = f"https://{domain}"

    directories = [
        "admin", "administrator", "backup", "backups", "blog", "cache", "cgi-bin", 
        "config", "css", "data", "dev", "docs", "download", "files", "images", 
        "includes", "js", "lib", "logs", "media", "modules", "old", "plugins", 
        "private", "public", "scripts", "src", "static", "temp", "test", "uploads", 
        "video", "web", "www", "backupdb", "backuptmp", "bin", "backupsql", "backupsdb", 
        "db", "database", "dbadmin", "dbbackup", "dbdump", "sql", "sqladmin", "sqldump", 
        "sqlbackup", "downloads", "dump", "testdb", "testsql", "tmp", "uploads", "users", 
        "usr", "webadmin", "webbackup", "webdb", "webdump", "websql", "install", 
        "installations"
    ]

    asyncio.run(domain_scanner(base_url, directories))

if __name__ == "__main__":
    main()
